language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis의 CI server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r rbwsn-springboot2-webservice *
  - mkdir -p deploy
  - mv rbwsn-springboot2-webservice.zip deploy/rbwsn-springboot2-webservice.zip

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # travis에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # travis에 설정된 값
      bucket: rbwsn-springboot-build # s3버킷
      region: ap-northeast-2 #아시아 태평양 서울
      skip_cleanup: true
      acl: private #zip파일 접근을 private로
      local_dir: deploy # before deploy로 생설한 디렉토리
      wait-until-deployed: true


notifications:
  email:
    recipients:
      - siosio0915@gmail.com